FROM stackhut/{{ baseos.name|lower }}:latest
MAINTAINER "StackHut" <stackhut@stackhut.com>
LABEL description="{{ stack.description }}"

{% if baseos_stack_pkgs %}
# install OS packages needed for stack
RUN echo "Starting..." && \
    {% for cmd in baseos.install_os_pkg(baseos_stack_pkgs) -%}
    {{ cmd }} && \
    {% endfor -%}
    echo "...done" && exit
{% endif %}
