FROM stackhut/{{ service.from_image }}:latest
MAINTAINER "{{ service.author }}" <{{ service.email }}>
LABEL description="{{ service.description }}"

{% if service.os_deps %}
# update the distro and commit
RUN echo "Starting..." && \
    {% for cmd in service.baseos.install_os_pkg(service.os_deps) -%}
    {{ cmd }} && \
    {% endfor -%}
    echo "...done" && exit
{% endif %}

# setup the env and copy all files and dirs across
WORKDIR /workdir
COPY Hutfile {{ service.stack.entrypoint }} {{ service.stack.get_install_stack_file }} {{ service.files|join(' ') }} ./
COPY .stackhut ./.stackhut
{% for d in service.dirs -%}
COPY {{ d }} ./{{ d }}
{% endfor -%}

{% if service.stack.get_install_stack_file %}
# install lang packages needed for stack
RUN {{ service.stack.install_stack_pkgs() }}
{% endif %}

# setup the entrypoint (using -vv for now)
ENTRYPOINT ["/usr/bin/python3", "/usr/bin/stackhut", "-vv", "run"]

# install stackhut app
RUN pip3 install --no-cache-dir --compile stackhut  # cache bust - {{ service.build_date }}

# any other Docker commands
{% for cmd in service.docker_cmds -%}
{{ cmd }}
{% endfor -%}

