FROM stackhut/{{ baseos.name|lower }}:latest
MAINTAINER "StackHut" <stackhut@stackhut.com>
LABEL description="{{ stack.description }}"

{% if baseos_stack_pkgs %}
# install OS packages needed for stack
RUN echo "Starting..." && \
    {% for cmd in baseos.install_os_pkg(baseos_stack_pkgs) -%}
    {{ cmd }} && \
    {% endfor -%}
    echo "...done" && exit
{% endif %}

WORKDIR /workdir

# copy the stackrun files into root
ONBUILD COPY ./Hutfile ./
ONBUILD COPY .stackhut ./.stackhut

# setup the python path
# ONBUILD ENV PYTHONPATH /stackhut/src
# setup the eventual entrypoint (using -vv for now)
ONBUILD ENTRYPOINT ["/usr/bin/python2", "/usr/bin/stackhut", "-vv", "run"]
