FROM {{ base.name|lower }}:latest
MAINTAINER "StackHut" <stackhut@stackhut.com>
LABEL description="{{ base.description }}"

# update the distro and commit
RUN echo "Starting..." && \
    {% for cmd in base.setup_cmds() -%}
    {{ cmd }} && \
    {% endfor -%}
    echo "...done" && exit
