FROM stackhut/{{ stack.name|lower }}:latest
MAINTAINER "StackHut" <stackhut@stackhut.com>
LABEL description="{{ stack.description }}"

# update the distro and commit
{% if stack_install_cmds %}
RUN echo "Starting..." && \
    {% for cmd in stack_install_cmds -%}
    {{ cmd }} && \
    {% endfor -%}
    echo "...done" && exit
{% endif %}

# copy the stackhut app
WORKDIR /workdir
ONBUILD COPY ./stackhut /stackhut

# copy the stackrun files into root
ONBUILD COPY ./.stackhut/service.json ./Hutfile ./
# setup the python path
ONBUILD ENV PYTHONPATH /stackhut/src
# setup the eventual entrypoint (using -vv for now)
ONBUILD ENTRYPOINT ["/usr/bin/python3", "/stackhut/src/stackhut.py", "-vv", "run"]

