FROM stackhut/{{ base.name|lower }}:latest
MAINTAINER "StackHut" <stackhut@stackhut.com>
LABEL description="{{ stack.description }}"

{% if stack_install_cmds %}
# install OS packages needed for stack
RUN echo "Starting..." && \
    {% for cmd in stack_install_cmds -%}
    {{ cmd }} && \
    {% endfor -%}
    echo "...done" && exit
{% endif %}

# copy the stackhut app
WORKDIR /workdir
ONBUILD COPY ./stackhut /stackhut
ONBUILD RUN pip3 install -r /stackhut/requirements.txt

# copy the stackrun files into root
ONBUILD COPY ./Hutfile ./
ONBUILD COPY .stackhut ./.stackhut

# setup the python path
ONBUILD ENV PYTHONPATH /stackhut/src
# setup the eventual entrypoint (using -vv for now)
ONBUILD ENTRYPOINT ["/usr/bin/python3", "/stackhut/src/stackhut.py", "-vv", "run"]

