FROM stackhut/{{ service.name }}:latest
MAINTAINER "{{ service.author }}" <{{ service.email }}>
LABEL description="{{ service.description }}"

# update the distro and commit
RUN echo "Starting..." && \
    {% for cmd in base.get_cmds() %}
    {{ cmd }} && \
    {% endfor %}
    echo "...done" && exit

# copy the application itself - needs to be done manually for now
COPY {{ service.entrypoint }} {{ service.files|join(' ') }} ./

# any other Docker commands
{% for cmd in service.docker_cmds %}
{{ cmd }}
{% endfor %}

